version: '3.8'
services:
  postgres:
    image: postgres:11  
    container_name: jira-postgres
    environment:
      POSTGRES_DB: #secret
      POSTGRES_USER: #secret
      POSTGRES_PASSWORD: #secret
      TZ: Europe/Moscow
      LC_COLLATE: "C"  
      LC_CTYPE: "C"    
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - jira-network
    restart: unless-stopped
  
  jira:
    build: ./jira-custom 
    container_name: jira-app
    image: custom-jira:8.12.0
    depends_on:
      - postgres
    environment:
      ATL_JDBC_URL: "jdbc:postgresql://postgres:5432/jiradb"
      ATL_JDBC_USER: #secret
      ATL_JDBC_PASSWORD: #secret
      TZ: Europe/Moscow
      JVM_SUPPORT_RECOMMENDED_ARGS: "-javaagent:/opt/jmx-exporter/jmx_prometheus_javaagent.jar=8081:/opt/jmx-exporter/config.yaml"
    volumes:
      - jira_data:/var/atlassian/application-data/jira
      - ./jmx-exporter:/opt/jmx-exporter
    ports:
      - "8080:8080"  
      - "8081:8081"  
    networks:
      - jira-network
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - "9090:9090"
    networks:
      - jira-network
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=#secret
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - jira-network
    restart: unless-stopped

volumes:
  postgres_data:
  jira_data:
  grafana_data:  

networks:
  jira-network:
    driver: bridge