name: Run API Tests

on:
  push:
    paths:
      - 'QA-portfolio/Auto testing/API Tests/test_reqres.py'
      - 'QA-portfolio/Auto testing/API Tests/conftest.py'
  pull_request:
    paths:
      - 'QA-portfolio/Auto testing/API Tests/test_reqres.py'
      - 'QA-portfolio/Auto testing/API Tests/conftest.py'

jobs:
  api-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest requests allure-pytest

    - name: Run API tests
      working-directory: ./QA-portfolio/Auto\ testing/API\ Tests
      run: |
        pytest -v test_reqres.py --alluredir=allure-results

    - name: Generate Allure report
      working-directory: ./QA-portfolio/Auto\ testing/API\ Tests
      run: |
        allure generate allure-results --clean -o allure-report

    - name: Upload Allure report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: allure-api-report
        path: QA-portfolio/Auto\ testing/API\ Tests/allure-report